# Site settings
title: El espacio de TeroRERO
titlefooter: Todos los Derechos Reservados #www.devinconde.com
myhead: Espacio de Devin R. Conde M.
powered: BITACORA d’ ROOT
urlpowered: http://bitacoraroot.com  #Link to external website
email: info@devinconde.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenido al espacio de Devin R. Conde M.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://terorero.github.io/resumen/" # the base hostname & protocol for your web site
# Build settings
markdown: kramdown_config.yml
